@BookingEngine_HostAddress = http://localhost:5010

### GET All Bookings by Client
GET {{BookingEngine_HostAddress}}/bookings
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIxIiwic3ViIjoidXNlcjEiLCJqdGkiOiI1ODY2YTBkNyIsInJvbGUiOiJDbGllbnQiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0MTAyMCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk0IiwiaHR0cDovL2xvY2FsaG9zdDo1MDEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMCJdLCJuYmYiOjE3ODYzNDA2MTksImV4cCI6MTc5NDI4OTQxOSwiaWF0IjoxNzg2MzQwNjIwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.VlMLdmh5ixGd_Ypgjl7nnM66cDbLcHTfRmF-VtkLXJg

### GET All Bookings by Admin
GET {{BookingEngine_HostAddress}}/bookings
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFTVVMiLCJzdWIiOiJBU1VTIiwianRpIjoiMzFlYTExNTIiLCJyb2xlIjoiQWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0MTAyMCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk0IiwiaHR0cDovL2xvY2FsaG9zdDo1MDEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMCJdLCJuYmYiOjE3ODYzMzkzMDIsImV4cCI6MTc5NDI4ODEwMiwiaWF0IjoxNzg2MzM5MzAzLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.GmpXSLimc4XE_Ikt0lWPY_5MmB8EsxzpG8xRzg9myYc

### GET Booking by ID
GET {{BookingEngine_HostAddress}}/bookings/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIxIiwic3ViIjoidXNlcjEiLCJqdGkiOiI1ODY2YTBkNyIsInJvbGUiOiJDbGllbnQiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0MTAyMCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk0IiwiaHR0cDovL2xvY2FsaG9zdDo1MDEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMCJdLCJuYmYiOjE3ODYzNDA2MTksImV4cCI6MTc5NDI4OTQxOSwiaWF0IjoxNzg2MzQwNjIwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.VlMLdmh5ixGd_Ypgjl7nnM66cDbLcHTfRmF-VtkLXJg

### POST Create New Booking
POST {{BookingEngine_HostAddress}}/bookings
Content-Type: application/json

{
  "roomId": 1,
  "CustomerName": "user2",
  "StartDate": "2026-04-01",
  "EndDate": "2026-04-07"
}

###
PUT {{BookingEngine_HostAddress}}/bookings/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIxIiwic3ViIjoidXNlcjEiLCJqdGkiOiI1ODY2YTBkNyIsInJvbGUiOiJDbGllbnQiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo0MTAyMCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0Mzk0IiwiaHR0cDovL2xvY2FsaG9zdDo1MDEwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEwMCJdLCJuYmYiOjE3ODYzNDA2MTksImV4cCI6MTc5NDI4OTQxOSwiaWF0IjoxNzg2MzQwNjIwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.VlMLdmh5ixGd_Ypgjl7nnM66cDbLcHTfRmF-VtkLXJg

{
  "roomId": 1,
  "CustomerName": "user1",
  "StartDate": "2026-09-01",
  "EndDate": "2026-09-05"
}

### DELETE Booking
DELETE {{BookingEngine_HostAddress}}/bookings/6
