@Host = http://localhost:5010

### 
GET {{Host}}/room-types
Accept: application/json

### 
GET {{Host}}/room-types/2
Accept: application/json

### 
POST {{Host}}/room-types
Content-Type: application/json

{
  "name": "Люкс 3 (Suite)",
  "description": "Двухкомнатный номер с видом на город"
}

### 
PUT {{Host}}/room-types/1
Content-Type: application/json

{
  "name": "Double",
  "description": "Two-room suite"
}

###
DELETE {{Host}}/room-types/3